### ISSUE TITLE
使用sdk 4.3 x5内核初始化失败

### ISSUE THREAD

**Issue by dogscar** [BzCoder/EasyX5WebView#1]
这个好像是腾讯x5官方的原因
华为 mate20
使用sdk 3.6 的内核就能正常初始化
使用sdk 4.3的就是内核初始化失败
那个liblbs.so文件还是3.6示例里面的，是不是这个原因

**Comment by BzCoder** [comment]
谢谢，试了下确实是这样。搜索了下也没找到4.3嵌入成功的例子。SDK先替换回3.6的版本了。

**Comment by BzCoder** [comment]
已解决不能加载问题
